version: '3.4'

services:
  teamspresencenograph:
    image: mrtechgadget/teamspresencenograph
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - <path>/config.json:config.json:ro
    ports:
      - 5000:5000
